const express=require('express')
const path=require('path')
const app=express()
app.use('/public', express.static(path.join(__dirname,'public')))
app.get('/',(req,res)=>res.send("Hello"))
app.listen(2323)